// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require('dotenv').config();
const { defineConfig, env } = require('prisma/config'); // Use the env helper
const { PrismaPg } = require('@prisma/adapter-pg');
const pg = require('pg');

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);

module.exports = defineConfig({
  schema: 'prisma/schema.prisma',
  // This nested datasource block is mandatory for migrations in v7
  datasource: {
    url: env("DATABASE_URL"), 
  },
  adapter, 
});
